name = "ar-app"
compatibility_date = "2025-03-07"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"
exclude = [
  ".git/**",
  ".DS_Store",
  "node_modules/**",
  "worker.js",
  "wrangler.toml",
]